import type { NextPage } from 'next'
import Head from 'next/head'
import { Typography, Row, Col } from 'antd';

import MainLayout from '../../components/main-layout';

import styles from '../../styles/team.module.sass';

const { Title } = Typography;

const TeamPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Row>
          <Col span={15}>
            <Row justify='space-around'>
              <Col span={23}>
                <Title className={styles.teamTitle} >Uventus</Title>
              </Col>
            </Row>
            <Row justify="space-around">
              <Col span={23}>
                <div className={styles.card}></div>
              </Col>
            </Row>
            <Row justify="space-around">
              <Col span={11}>
                <div className={styles.card}></div>
              </Col>
              <Col span={11}>
                <div className={styles.card}></div>
              </Col>
            </Row>
            <Row justify="space-around">
              <Col span={23}>
                <div className={styles.card}></div>
              </Col>
            </Row>
          </Col>
          <Col span={9}>
            <div className={styles.details}></div>
          </Col>
        </Row>
      </MainLayout>
    </>
  )
}

export default TeamPage;
