import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout, Menu, Typography, Row, Col } from 'antd';
import {
  UserOutlined,
  GlobalOutlined
} from '@ant-design/icons';
import "antd/dist/antd.css";
import styles from '../styles/team.module.sass';

const { Header, Sider, Content, Footer } = Layout;
const { Title } = Typography;

const colBackground = { background: 'grey', height: '7rem' }

const TeamPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className={styles.container}>
        <Header className={styles.header}>
          <GlobalOutlined className={styles.logo} />
          <div>
            <h1>Soccer Dashboard</h1>
          </div>
        </Header>
        <Layout>
          <Sider>
            <Menu theme="dark" mode="inline" defaultSelectedKeys={['1']}>
              <Menu.Item key="1" icon={<UserOutlined />}>
                Команда 1
              </Menu.Item>
              <Menu.Item key="2" icon={<UserOutlined />}>
                Команда 2
              </Menu.Item>
              <Menu.Item key="3" icon={<UserOutlined />}>
                Команда 3
              </Menu.Item>
            </Menu>
          </Sider>
          <Content>
            <Row>
              <Col span={15}>
                <Row justify='space-around'>
                  <Col span={23}>
                    <Title className={styles.teamTitle} >Uventus</Title>
                  </Col>
                </Row>
                <Row justify="space-around">
                  <Col span={23}>
                    <div className={styles.card}></div>
                  </Col>
                </Row>
                <Row justify="space-around">
                  <Col span={11}>
                    <div className={styles.card}></div>
                  </Col>
                  <Col span={11}>
                    <div className={styles.card}></div>
                  </Col>
                </Row>
                <Row justify="space-around">
                  <Col span={23}>
                    <div className={styles.card}></div>
                  </Col>
                </Row>
              </Col>
              <Col span={9}>
                <div className={styles.details}></div>
              </Col>
            </Row>
          </Content>
        </Layout>
        
      </Layout>
    </>
  )
}

export default TeamPage;
