import type { NextPage } from 'next';
import Head from 'next/head';
import { Row, Col } from 'antd';

import MainLayout from '../components/main-layout';
import LeaderCard from '../components/leader-card';
import Goals from '../components/goals';
import Kicks from '../components/kicks';
import TodayCard from '../components/today-card';
import TomorrowCard from '../components/tomorrow-card';
import YesterdayCard from '../components/yesterday-card';

import styles from '../styles/home.module.sass';

const Home: NextPage = () => {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <Row>
                    <Col span={16}>
                        <Row justify='space-around'>
                            <Col span={23} >
                                <div className={styles.cardWrapper}>
                                    <LeaderCard />
                                </div>
                            </Col>
                        </Row>
                        <Row justify='space-around'>
                            <Col span={11}>
                                <div className={styles.cardWrapper}>
                                    <Goals />
                                </div>
                            </Col>
                            <Col span={11}>
                                <div className={styles.cardWrapper}>
                                    <Kicks />
                                </div>
                            </Col>
                        </Row>
                        <Row justify='space-around'>
                            <Col span={23}>
                                <div className={styles.cardWrapper}>
                                    <TodayCard />
                                </div>
                            </Col>
                        </Row>
                        <Row justify='space-around'>
                            <Col span={23}>
                                <div className={styles.cardWrapper}>
                                    <TomorrowCard />
                                </div>
                            </Col>
                        </Row>
                    </Col>
                    <Col span={8}>
                        <div className={styles.cardWrapper}>
                            <YesterdayCard />
                        </div>
                        <div className={styles.cardWrapper}>
                            <YesterdayCard />
                        </div>
                        <div className={styles.cardWrapper}>
                            <YesterdayCard />
                        </div>
                        <div className={styles.cardWrapper}>
                            <YesterdayCard />
                        </div>
                    </Col>
                </Row>
            </MainLayout>    
        </>
    );
}

export default Home;