import type { NextPage } from 'next';
import Head from 'next/head';
import { Layout, Menu, Row, Col } from 'antd';
import { GlobalOutlined, UserOutlined } from '@ant-design/icons';

import "antd/dist/antd.css";
import styleHeader from '../styles/team.module.sass';
import styles from '../styles/home.module.sass';

const { Header, Sider, Content } = Layout;

const Home: NextPage = () => {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Header className={styleHeader.header}>
                    <GlobalOutlined className={styleHeader.logo} />
                    <div>
                        <h1>Soccer Dashboard</h1>
                    </div>
                </Header>
                <Layout>
                    <Sider>
                    <Menu theme="dark" mode="inline" defaultSelectedKeys={['1']}>
                        <Menu.Item key="1" icon={<UserOutlined />}>
                            Команда 1
                        </Menu.Item>
                        <Menu.Item key="2" icon={<UserOutlined />}>
                            Команда 2
                        </Menu.Item>
                        <Menu.Item key="3" icon={<UserOutlined />}>
                            Команда 3
                        </Menu.Item>
                    </Menu>
                    </Sider>
                    <Content>
                        <Row>
                            <Col span={16}>
                                <Row justify='space-around'>
                                    <Col span={23} >
                                        <div className={styles.cardLider}></div>
                                    </Col>
                                </Row>
                                <Row justify='space-around'>
                                    <Col span={11}>
                                        <div className={styles.cardDiagram}></div>
                                    </Col>
                                    <Col span={11}>
                                        <div className={styles.cardDiagram}></div>
                                    </Col>
                                </Row>
                                <Row justify='space-around'>
                                    <Col span={23}>
                                        <div className={styles.cardLider}></div>
                                    </Col>
                                </Row>
                                <Row justify='space-around'>
                                    <Col span={23}>
                                        <div className={styles.cardLider}></div>
                                    </Col>
                                </Row>
                            </Col>
                            <Col span={7}>
                                <div className={styles.cardDiagram}></div>
                                <div className={styles.cardDiagram}></div>
                                <div className={styles.cardDiagram}></div>
                                <div className={styles.cardDiagram}></div>
                            </Col>
                        </Row>
                    </Content>
                </Layout>
            </Layout>
        </>
    );
}

export default Home;